### ISSUE TITLE
should colons be used to delimit subtitles?

### ISSUE THREAD

**Issue by eshellman** [gutenbergtools/libgutenberg#26]
https://github.com/gutenbergtools/ebookmaker/issues/154

**Comment by eshellman** [comment]
There are three different issues relating to subtitles -
1. how do we include subtitles into the database.
2. how do we render a subtitle with without its subtitle.
3. how are we instructing people to recognize and enter subtitles?

#1 and # 2 depend a lot on #3; I need help understanding this.
There are clear issues in how we do #2. 
@gbnewby @asylumcs

**Comment by nfenwick** [comment]
For (1), that's Eric and Greg, but (2) nearly dictates that there be two separate entities if you want to render the title alone since normal punctuation will have exceptions unless you choose something that would never show up in a title or subtitle, like a vertical pipe '|' symbol. For (3), I'll research this with DP. They do get two fields to fill in on the submissions form, one for Title and one for Subtitle. But still, there are probably open questions that DP may/may not have addressed. For example, if the subtitle is in sentence case separately from the title, then when they are combined there easily could be a visually disturbing capitalization. This problem goes away if there is one (combined) title line end to end in our toolchain (the way the copyright was registered). But if we make our title match the copyright title, then there is no reliable way to "render a title without its subtitle", assuming bullet item 2 is a must-have.

**Comment by nfenwick** [comment]
Sorry, Nell is asylumcs (Roger). I was (again) logged in as Nell because I've been working in the gutenbergbooks repository on repos that were created by her scripts.

**Comment by eshellman** [comment]
We use the `tiitle_no_subtitle()` method in a few places to render the titles where very long, possibly multiline titles would not work. the current implementation is to truncate the title at the first newline or colon. In other places we truncate the title based on length without regard to the subtitle. looking at the uses, it's not absolutely necessary, given the alternative of length-based truncation.
