### ISSUE TITLE
Bad comma treatment for some creators

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/libgutenberg#43]
This issue emerged when looking into the other problem I reported with punctuation.

My understanding of the issue is that Creator entries are stored in the catalog database with commas, such as:

Carroll, Lewis

There is no separate field for firstname/lastname, and (unlike the Title field) there is no notion of non-filing characters. In autocat3, the author death/birth dates are added (from different fields) so the landing page such as https://www.gutenberg.org/ebooks/11 shows:

Carroll, Lewis, 1832-1898

The problem is that the Creator fields (Author, Publisher, Editor, Illustrator, etc.) reorder the author name for the generated files and the top line of the landing page.

This reordering is not always correct. Here are some examples:

https://www.gutenberg.org/ebooks/60880
https://www.gutenberg.org/ebooks/37658
https://www.gutenberg.org/ebooks/61205
https://www.gutenberg.org/ebooks/55424

A partial solution would be to not reorder when the Creator type is Publisher. (And then, fix some records where the Publisher is listed as Author, though this might not be the catalogers' preference.)

That doesn't address all the situations, though - sometimes the comma is a legitimate part of the Author's "name."

Some possible approaches:

(1) in the author record if the "role" field is "Publisher", then use as-is.  

(2) there is an "alias" field in the author record. We could use that to show how it should be displayed. For example, "Little, Brown and Company" could be in the alias field as "[Little, Brown and Company]" 

(3) Indicate which commas aren't fungible, such as using "Little\, Brown and Company". 

There seems to be enough of these that a fix of some sort is desirable. I could work with Roger to make a more complete list, if desired.

**Comment by asylumcs** [comment]
I believe on option #3 an intended leading slash on the comma after "Little" was consumed when the post was displayed. I believe option #3 should be "Little\\, Brown and Company".

**Comment by eshellman** [comment]
I have added code that suppresses name reordering and surname extraction when the author is a publisher. (solution # 1)

The best solution, (#4) one that should be implemented in the future, is to add a column in the author table to indicate that the author (we use this table for a variety of relations, including editor, translator, illustrator, etc) is an organization rather than a natural person. This is needed to make correct MARC records, which is something that my colleague Ray Schwartz has been working on.

solutions # 2 and # 3 are unwise because they increase complexity and break other downstream metadata feeds.

**Comment by gbnewby** [comment]
Thanks!
